from __future__ import annotations


StockCatalogRow = tuple[str, str, str, str, str, str | None, str | None, str, str]


SEED_STOCK_CATALOG: tuple[StockCatalogRow, ...] = (
    ("A.TO", "A.TO", "XTSE", "CAD", "Agnico Eagle Mines Limited", "Basic Materials", "Gold", "CA", "North America"),
    ("ATD.TO", "ATD.TO", "XTSE", "CAD", "Alimentation Couche-Tard Inc.", "Consumer Cyclical", "Specialty Retail", "CA", "North America"),
    ("BMO.TO", "BMO.TO", "XTSE", "CAD", "Bank of Montreal", "Financial Services", "Banks", "CA", "North America"),
    ("BNS.TO", "BNS.TO", "XTSE", "CAD", "Bank of Nova Scotia", "Financial Services", "Banks", "CA", "North America"),
    ("ABX.TO", "ABX.TO", "XTSE", "CAD", "Barrick Gold Corporation", "Basic Materials", "Gold", "CA", "North America"),
    ("BCE.TO", "BCE.TO", "XTSE", "CAD", "BCE Inc.", "Communication Services", "Telecom Services", "CA", "North America"),
    ("BAM.TO", "BAM.TO", "XTSE", "CAD", "Brookfield Asset Management Ltd.", "Financial Services", "Asset Management", "CA", "North America"),
    ("BN.TO", "BN.TO", "XTSE", "CAD", "Brookfield Corporation", "Financial Services", "Asset Management", "CA", "North America"),
    ("BIP-UN.TO", "BIP-UN.TO", "XTSE", "CAD", "Brookfield Infrastructure Partners L.P.", "Utilities", "Utilities Diversified", "CA", "North America"),
    ("CAE.TO", "CAE.TO", "XTSE", "CAD", "CAE Inc.", "Industrials", "Aerospace & Defense", "CA", "North America"),
    ("CCO.TO", "CCO.TO", "XTSE", "CAD", "Cameco Corporation", "Energy", "Uranium", "CA", "North America"),
    ("CM.TO", "CM.TO", "XTSE", "CAD", "Canadian Imperial Bank of Commerce", "Financial Services", "Banks", "CA", "North America"),
    ("CNR.TO", "CNR.TO", "XTSE", "CAD", "Canadian National Railway Company", "Industrials", "Railroads", "CA", "North America"),
    ("CNQ.TO", "CNQ.TO", "XTSE", "CAD", "Canadian Natural Resources Limited", "Energy", "Oil & Gas E&P", "CA", "North America"),
    ("CP.TO", "CP.TO", "XTSE", "CAD", "Canadian Pacific Kansas City Limited", "Industrials", "Railroads", "CA", "North America"),
    ("CTC-A.TO", "CTC-A.TO", "XTSE", "CAD", "Canadian Tire Corporation Limited", "Consumer Cyclical", "Specialty Retail", "CA", "North America"),
    ("CVE.TO", "CVE.TO", "XTSE", "CAD", "Cenovus Energy Inc.", "Energy", "Oil & Gas Integrated", "CA", "North America"),
    ("CSU.TO", "CSU.TO", "XTSE", "CAD", "Constellation Software Inc.", "Technology", "Software", "CA", "North America"),
    ("DOL.TO", "DOL.TO", "XTSE", "CAD", "Dollarama Inc.", "Consumer Defensive", "Discount Stores", "CA", "North America"),
    ("EMA.TO", "EMA.TO", "XTSE", "CAD", "Emera Incorporated", "Utilities", "Utilities Regulated Electric", "CA", "North America"),
    ("ENB.TO", "ENB.TO", "XTSE", "CAD", "Enbridge Inc.", "Energy", "Oil & Gas Midstream", "CA", "North America"),
    ("FM.TO", "FM.TO", "XTSE", "CAD", "First Quantum Minerals Ltd.", "Basic Materials", "Copper", "CA", "North America"),
    ("FNV.TO", "FNV.TO", "XTSE", "CAD", "Franco-Nevada Corporation", "Basic Materials", "Gold", "CA", "North America"),
    ("FTS.TO", "FTS.TO", "XTSE", "CAD", "Fortis Inc.", "Utilities", "Utilities Regulated Electric", "CA", "North America"),
    ("GIB-A.TO", "GIB-A.TO", "XTSE", "CAD", "CGI Inc.", "Technology", "Information Technology Services", "CA", "North America"),
    ("GIL.TO", "GIL.TO", "XTSE", "CAD", "Gildan Activewear Inc.", "Consumer Cyclical", "Apparel Manufacturing", "CA", "North America"),
    ("H.TO", "H.TO", "XTSE", "CAD", "Hydro One Limited", "Utilities", "Utilities Regulated Electric", "CA", "North America"),
    ("IFC.TO", "IFC.TO", "XTSE", "CAD", "Intact Financial Corporation", "Financial Services", "Insurance Property & Casualty", "CA", "North America"),
    ("IMO.TO", "IMO.TO", "XTSE", "CAD", "Imperial Oil Limited", "Energy", "Oil & Gas Integrated", "CA", "North America"),
    ("K.TO", "K.TO", "XTSE", "CAD", "Kinross Gold Corporation", "Basic Materials", "Gold", "CA", "North America"),
    ("L.TO", "L.TO", "XTSE", "CAD", "Loblaw Companies Limited", "Consumer Defensive", "Grocery Stores", "CA", "North America"),
    ("MFC.TO", "MFC.TO", "XTSE", "CAD", "Manulife Financial Corporation", "Financial Services", "Insurance Life", "CA", "North America"),
    ("MG.TO", "MG.TO", "XTSE", "CAD", "Magna International Inc.", "Consumer Cyclical", "Auto Parts", "CA", "North America"),
    ("MRU.TO", "MRU.TO", "XTSE", "CAD", "Metro Inc.", "Consumer Defensive", "Grocery Stores", "CA", "North America"),
    ("NA.TO", "NA.TO", "XTSE", "CAD", "National Bank of Canada", "Financial Services", "Banks", "CA", "North America"),
    ("NTR.TO", "NTR.TO", "XTSE", "CAD", "Nutrien Ltd.", "Basic Materials", "Agricultural Inputs", "CA", "North America"),
    ("OTEX.TO", "OTEX.TO", "XTSE", "CAD", "Open Text Corporation", "Technology", "Software", "CA", "North America"),
    ("POW.TO", "POW.TO", "XTSE", "CAD", "Power Corporation of Canada", "Financial Services", "Insurance Diversified", "CA", "North America"),
    ("QSR.TO", "QSR.TO", "XTSE", "CAD", "Restaurant Brands International Inc.", "Consumer Cyclical", "Restaurants", "CA", "North America"),
    ("RCI-B.TO", "RCI-B.TO", "XTSE", "CAD", "Rogers Communications Inc.", "Communication Services", "Telecom Services", "CA", "North America"),
    ("RY.TO", "RY.TO", "XTSE", "CAD", "Royal Bank of Canada", "Financial Services", "Banks", "CA", "North America"),
    ("SAP.TO", "SAP.TO", "XTSE", "CAD", "Saputo Inc.", "Consumer Defensive", "Packaged Foods", "CA", "North America"),
    ("SHOP.TO", "SHOP.TO", "XTSE", "CAD", "Shopify Inc.", "Technology", "Software", "CA", "North America"),
    ("SLF.TO", "SLF.TO", "XTSE", "CAD", "Sun Life Financial Inc.", "Financial Services", "Insurance Life", "CA", "North America"),
    ("SU.TO", "SU.TO", "XTSE", "CAD", "Suncor Energy Inc.", "Energy", "Oil & Gas Integrated", "CA", "North America"),
    ("T.TO", "T.TO", "XTSE", "CAD", "TELUS Corporation", "Communication Services", "Telecom Services", "CA", "North America"),
    ("TD.TO", "TD.TO", "XTSE", "CAD", "Toronto-Dominion Bank", "Financial Services", "Banks", "CA", "North America"),
    ("TECK-B.TO", "TECK-B.TO", "XTSE", "CAD", "Teck Resources Limited", "Basic Materials", "Other Industrial Metals", "CA", "North America"),
    ("TRI.TO", "TRI.TO", "XTSE", "CAD", "Thomson Reuters Corporation", "Industrials", "Specialty Business Services", "CA", "North America"),
    ("TRP.TO", "TRP.TO", "XTSE", "CAD", "TC Energy Corporation", "Energy", "Oil & Gas Midstream", "CA", "North America"),
    ("WCN.TO", "WCN.TO", "XTSE", "CAD", "Waste Connections Inc.", "Industrials", "Waste Management", "CA", "North America"),
    ("WPM.TO", "WPM.TO", "XTSE", "CAD", "Wheaton Precious Metals Corp.", "Basic Materials", "Gold", "CA", "North America"),
    ("WSP.TO", "WSP.TO", "XTSE", "CAD", "WSP Global Inc.", "Industrials", "Engineering & Construction", "CA", "North America"),
    ("ABBV", "ABBV", "XNYS", "USD", "AbbVie Inc.", "Healthcare", "Drug Manufacturers General", "US", "North America"),
    ("ABT", "ABT", "XNYS", "USD", "Abbott Laboratories", "Healthcare", "Medical Devices", "US", "North America"),
    ("ACN", "ACN", "XNYS", "USD", "Accenture plc", "Technology", "Information Technology Services", "US", "North America"),
    ("AIG", "AIG", "XNYS", "USD", "American International Group Inc.", "Financial Services", "Insurance Diversified", "US", "North America"),
    ("AMT", "AMT", "XNYS", "USD", "American Tower Corporation", "Real Estate", "REIT Specialty", "US", "North America"),
    ("AXP", "AXP", "XNYS", "USD", "American Express Company", "Financial Services", "Credit Services", "US", "North America"),
    ("BA", "BA", "XNYS", "USD", "Boeing Company", "Industrials", "Aerospace & Defense", "US", "North America"),
    ("BAC", "BAC", "XNYS", "USD", "Bank of America Corporation", "Financial Services", "Banks", "US", "North America"),
    ("BMY", "BMY", "XNYS", "USD", "Bristol-Myers Squibb Company", "Healthcare", "Drug Manufacturers General", "US", "North America"),
    ("BRK-B", "BRK-B", "XNYS", "USD", "Berkshire Hathaway Inc.", "Financial Services", "Insurance Diversified", "US", "North America"),
    ("CAT", "CAT", "XNYS", "USD", "Caterpillar Inc.", "Industrials", "Farm & Heavy Construction Machinery", "US", "North America"),
    ("CL", "CL", "XNYS", "USD", "Colgate-Palmolive Company", "Consumer Defensive", "Household & Personal Products", "US", "North America"),
    ("COF", "COF", "XNYS", "USD", "Capital One Financial Corporation", "Financial Services", "Credit Services", "US", "North America"),
    ("COP", "COP", "XNYS", "USD", "ConocoPhillips", "Energy", "Oil & Gas E&P", "US", "North America"),
    ("CVX", "CVX", "XNYS", "USD", "Chevron Corporation", "Energy", "Oil & Gas Integrated", "US", "North America"),
    ("DE", "DE", "XNYS", "USD", "Deere & Company", "Industrials", "Farm & Heavy Construction Machinery", "US", "North America"),
    ("DIS", "DIS", "XNYS", "USD", "Walt Disney Company", "Communication Services", "Entertainment", "US", "North America"),
    ("DUK", "DUK", "XNYS", "USD", "Duke Energy Corporation", "Utilities", "Utilities Regulated Electric", "US", "North America"),
    ("EL", "EL", "XNYS", "USD", "Estee Lauder Companies Inc.", "Consumer Defensive", "Household & Personal Products", "US", "North America"),
    ("EMR", "EMR", "XNYS", "USD", "Emerson Electric Co.", "Industrials", "Specialty Industrial Machinery", "US", "North America"),
    ("F", "F", "XNYS", "USD", "Ford Motor Company", "Consumer Cyclical", "Auto Manufacturers", "US", "North America"),
    ("FDX", "FDX", "XNYS", "USD", "FedEx Corporation", "Industrials", "Integrated Freight & Logistics", "US", "North America"),
    ("GE", "GE", "XNYS", "USD", "GE Aerospace", "Industrials", "Aerospace & Defense", "US", "North America"),
    ("GM", "GM", "XNYS", "USD", "General Motors Company", "Consumer Cyclical", "Auto Manufacturers", "US", "North America"),
    ("GS", "GS", "XNYS", "USD", "Goldman Sachs Group Inc.", "Financial Services", "Capital Markets", "US", "North America"),
    ("HD", "HD", "XNYS", "USD", "Home Depot Inc.", "Consumer Cyclical", "Home Improvement Retail", "US", "North America"),
    ("HON", "HON", "XNYS", "USD", "Honeywell International Inc.", "Industrials", "Conglomerates", "US", "North America"),
    ("IBM", "IBM", "XNYS", "USD", "International Business Machines Corporation", "Technology", "Information Technology Services", "US", "North America"),
    ("JNJ", "JNJ", "XNYS", "USD", "Johnson & Johnson", "Healthcare", "Drug Manufacturers General", "US", "North America"),
    ("JPM", "JPM", "XNYS", "USD", "JPMorgan Chase & Co.", "Financial Services", "Banks", "US", "North America"),
    ("KO", "KO", "XNYS", "USD", "Coca-Cola Company", "Consumer Defensive", "Beverages Non-Alcoholic", "US", "North America"),
    ("LOW", "LOW", "XNYS", "USD", "Lowe's Companies Inc.", "Consumer Cyclical", "Home Improvement Retail", "US", "North America"),
    ("MA", "MA", "XNYS", "USD", "Mastercard Incorporated", "Financial Services", "Credit Services", "US", "North America"),
    ("MCD", "MCD", "XNYS", "USD", "McDonald's Corporation", "Consumer Cyclical", "Restaurants", "US", "North America"),
    ("MMM", "MMM", "XNYS", "USD", "3M Company", "Industrials", "Conglomerates", "US", "North America"),
    ("MRK", "MRK", "XNYS", "USD", "Merck & Co. Inc.", "Healthcare", "Drug Manufacturers General", "US", "North America"),
    ("NEE", "NEE", "XNYS", "USD", "NextEra Energy Inc.", "Utilities", "Utilities Regulated Electric", "US", "North America"),
    ("NKE", "NKE", "XNYS", "USD", "NIKE Inc.", "Consumer Cyclical", "Footwear & Accessories", "US", "North America"),
    ("ORCL", "ORCL", "XNYS", "USD", "Oracle Corporation", "Technology", "Software Infrastructure", "US", "North America"),
    ("PEP", "PEP", "XNYS", "USD", "PepsiCo Inc.", "Consumer Defensive", "Beverages Non-Alcoholic", "US", "North America"),
    ("PFE", "PFE", "XNYS", "USD", "Pfizer Inc.", "Healthcare", "Drug Manufacturers General", "US", "North America"),
    ("PG", "PG", "XNYS", "USD", "Procter & Gamble Company", "Consumer Defensive", "Household & Personal Products", "US", "North America"),
    ("PM", "PM", "XNYS", "USD", "Philip Morris International Inc.", "Consumer Defensive", "Tobacco", "US", "North America"),
    ("RTX", "RTX", "XNYS", "USD", "RTX Corporation", "Industrials", "Aerospace & Defense", "US", "North America"),
    ("SBUX", "SBUX", "XNYS", "USD", "Starbucks Corporation", "Consumer Cyclical", "Restaurants", "US", "North America"),
    ("SCHW", "SCHW", "XNYS", "USD", "Charles Schwab Corporation", "Financial Services", "Capital Markets", "US", "North America"),
    ("SO", "SO", "XNYS", "USD", "Southern Company", "Utilities", "Utilities Regulated Electric", "US", "North America"),
    ("T", "T", "XNYS", "USD", "AT&T Inc.", "Communication Services", "Telecom Services", "US", "North America"),
    ("TGT", "TGT", "XNYS", "USD", "Target Corporation", "Consumer Defensive", "Discount Stores", "US", "North America"),
    ("TRV", "TRV", "XNYS", "USD", "Travelers Companies Inc.", "Financial Services", "Insurance Property & Casualty", "US", "North America"),
    ("UNH", "UNH", "XNYS", "USD", "UnitedHealth Group Incorporated", "Healthcare", "Healthcare Plans", "US", "North America"),
    ("UNP", "UNP", "XNYS", "USD", "Union Pacific Corporation", "Industrials", "Railroads", "US", "North America"),
    ("UPS", "UPS", "XNYS", "USD", "United Parcel Service Inc.", "Industrials", "Integrated Freight & Logistics", "US", "North America"),
    ("V", "V", "XNYS", "USD", "Visa Inc.", "Financial Services", "Credit Services", "US", "North America"),
    ("VZ", "VZ", "XNYS", "USD", "Verizon Communications Inc.", "Communication Services", "Telecom Services", "US", "North America"),
    ("WFC", "WFC", "XNYS", "USD", "Wells Fargo & Company", "Financial Services", "Banks", "US", "North America"),
    ("WMT", "WMT", "XNYS", "USD", "Walmart Inc.", "Consumer Defensive", "Discount Stores", "US", "North America"),
    ("XOM", "XOM", "XNYS", "USD", "Exxon Mobil Corporation", "Energy", "Oil & Gas Integrated", "US", "North America"),
)


def seed_stock_catalog(conn) -> int:
    conn.executemany(
        """
        INSERT INTO stock_catalog (
            asset_id,
            symbol,
            exchange_code,
            ccy,
            name,
            sector,
            industry,
            country,
            region,
            asset_type,
            source,
            created_at,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'stock', 'static_seed', now(), now())
        ON CONFLICT (asset_id)
        DO UPDATE SET
            symbol = excluded.symbol,
            exchange_code = excluded.exchange_code,
            ccy = excluded.ccy,
            name = excluded.name,
            sector = excluded.sector,
            industry = excluded.industry,
            country = excluded.country,
            region = excluded.region,
            updated_at = now()
        """,
        SEED_STOCK_CATALOG,
    )
    row = conn.execute("SELECT COUNT(*) FROM stock_catalog").fetchone()
    return int(row[0])
