FUNDAMENTALS_REFRESH_JOB = "fundamentals-refresh"

DEFAULT_REFRESH_INTERVAL_DAYS = 7

FUNDAMENTAL_REFRESH_DATASET = "financial_statements"
FUNDAMENTAL_REFRESH_MODE = "refresh"

JOB_STATUS_QUEUED = "queued"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_DONE = "done"
JOB_STATUS_FAILED = "failed"

OPEN_JOB_STATUSES = (JOB_STATUS_QUEUED, JOB_STATUS_RUNNING)