"""Provider-neutral deterministic candidate-engine contracts."""

from dashboard.ai_brain.candidates.canonical import (
    VOLATILE_HASH_FIELDS,
    candidate_evidence_id,
    candidate_id,
    candidate_review_id,
    candidate_run_id,
    canonical_hash,
    canonical_json,
)
from dashboard.ai_brain.candidates.models import (
    CANDIDATE_EVIDENCE_SCHEMA_VERSION,
    CANDIDATE_METHODOLOGY_VERSION,
    CANDIDATE_REASON_CODES_VERSION,
    CANDIDATE_REVIEW_SCHEMA_VERSION,
    CANDIDATE_RUN_SCHEMA_VERSION,
    CandidateEvidenceRef,
    CandidateHighlight,
    CandidateMissingMetric,
    CandidateReview,
    CandidateRun,
    CandidateScore,
    CandidateScoreComponent,
    CandidateSourceMatch,
    CandidateSourceWatermark,
    CandidateWarning,
)
from dashboard.ai_brain.candidates.persistence import (
    CandidatePersistenceConflict,
    CandidatePersistenceError,
    CandidatePersistenceIntegrityError,
    CandidateRunRepository,
    ensure_candidate_schema,
)
from dashboard.ai_brain.candidates.serialization import candidate_review_from_json
from dashboard.ai_brain.candidates.source_adapters import (
    ALL_UNIVERSE_SCHEMA_VERSION,
    BENCHMARK_CONSTITUENT_SCHEMA_VERSION,
    CANDIDATE_SOURCE_ADAPTER_VERSION,
    STOCK_RANKING_SCHEMA_VERSION,
    WATCHLIST_SCHEMA_VERSION,
    CandidateNomination,
    CandidateSourceAdapters,
    SourceAdapterResult,
)
from dashboard.ai_brain.candidates.universe import (
    IDENTITY_METHODOLOGY_VERSION,
    BlockedCandidateIdentity,
    CandidateAssetIdentityResolver,
    CandidatePoolExclusion,
    CandidatePoolItem,
    CandidatePoolResult,
    OutsideHoldingUniverseBuilder,
    ResolvedCandidateIdentity,
)

__all__ = [
    "ALL_UNIVERSE_SCHEMA_VERSION",
    "BENCHMARK_CONSTITUENT_SCHEMA_VERSION",
    "CANDIDATE_EVIDENCE_SCHEMA_VERSION",
    "CANDIDATE_METHODOLOGY_VERSION",
    "CANDIDATE_REASON_CODES_VERSION",
    "CANDIDATE_REVIEW_SCHEMA_VERSION",
    "CANDIDATE_RUN_SCHEMA_VERSION",
    "CANDIDATE_SOURCE_ADAPTER_VERSION",
    "IDENTITY_METHODOLOGY_VERSION",
    "STOCK_RANKING_SCHEMA_VERSION",
    "VOLATILE_HASH_FIELDS",
    "WATCHLIST_SCHEMA_VERSION",
    "BlockedCandidateIdentity",
    "CandidateAssetIdentityResolver",
    "CandidateEvidenceRef",
    "CandidateHighlight",
    "CandidateMissingMetric",
    "CandidateNomination",
    "CandidatePersistenceConflict",
    "CandidatePersistenceError",
    "CandidatePersistenceIntegrityError",
    "CandidatePoolExclusion",
    "CandidatePoolItem",
    "CandidatePoolResult",
    "CandidateReview",
    "CandidateRun",
    "CandidateRunRepository",
    "CandidateScore",
    "CandidateScoreComponent",
    "CandidateSourceAdapters",
    "CandidateSourceMatch",
    "CandidateSourceWatermark",
    "CandidateWarning",
    "OutsideHoldingUniverseBuilder",
    "ResolvedCandidateIdentity",
    "SourceAdapterResult",
    "candidate_evidence_id",
    "candidate_id",
    "candidate_review_from_json",
    "candidate_review_id",
    "candidate_run_id",
    "canonical_hash",
    "canonical_json",
    "ensure_candidate_schema",
]
