"""
constants for domain A data ingestion
"""

DOMAIN_MARKET = "market"

JOB_TYPE_BACKFILL = "backfill"
JOB_TYPE_REFRESH = "refresh"

DATASET_PRICE_DAILY = "price_daily"
DATASET_DIVIDENDS = "dividends"
DATASET_SPLITS = "splits"

STATUS_PENDING = "pending"
STATUS_RUNNING = "running"
STATUS_DONE = "done"
STATUS_FAILED = "failed"

BACKFILL_NOT_STARTED = "not_started"
BACKFILL_RUNNING = "running"
BACKFILL_DONE = "done"
BACKFILL_FAILED = "failed"

PRIORITY_MARKET_REFRESH_PRICE = 100
PRIORITY_MARKET_REFRESH_DIVIDENDS = 90
PRIORITY_MARKET_REFRESH_SPLITS = 80

PRIORITY_MARKET_BACKFILL_PRICE = 50
PRIORITY_MARKET_BACKFILL_DIVIDENDS = 40
PRIORITY_MARKET_BACKFILL_SPLITS = 30