CORE_INDICES = [
    {
        "index_id": "SP500",
        "index_name": "S&P 500",
        "index_family": "S&P",
        "index_category": "core_geo",
        "region": "North America",
        "country_code": "US",
        "currency": "USD",
        "is_core": True,
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "^GSPC", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": False},
            {"provider": "yfinance", "provider_symbol": "^GSPC", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": False},
            {"provider": "fmp", "provider_symbol": "^GSPC", "symbol_purpose": "price_daily", "is_primary": False, "is_proxy": False},
            {"provider": "fmp", "provider_symbol": "^GSPC", "symbol_purpose": "price_intraday", "is_primary": False, "is_proxy": False},
            {"provider": "fmp", "provider_symbol": "sp500-constituent", "symbol_purpose": "constituents", "is_primary": True, "is_proxy": False},
            {"provider": "etf_proxy", "provider_symbol": "SPY", "symbol_purpose": "proxy_holdings", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "NDX100",
        "index_name": "Nasdaq 100",
        "index_family": "Nasdaq",
        "index_category": "core_geo",
        "region": "North America",
        "country_code": "US",
        "currency": "USD",
        "is_core": True,
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "^NDX", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": False},
            {"provider": "yfinance", "provider_symbol": "^NDX", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": False},
            {"provider": "fmp", "provider_symbol": "^NDX", "symbol_purpose": "price_daily", "is_primary": False, "is_proxy": False},
            {"provider": "fmp", "provider_symbol": "^NDX", "symbol_purpose": "price_intraday", "is_primary": False, "is_proxy": False},
            {"provider": "etf_proxy", "provider_symbol": "QQQ", "symbol_purpose": "proxy_holdings", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "TSXCOMP",
        "index_name": "S&P/TSX Composite",
        "index_family": "S&P/TSX",
        "index_category": "core_geo",
        "region": "North America",
        "country_code": "CA",
        "currency": "CAD",
        "is_core": True,
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "^GSPTSE", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": False},
            {"provider": "yfinance", "provider_symbol": "^GSPTSE", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": False},
            {"provider": "etf_proxy", "provider_symbol": "XIC.TO", "symbol_purpose": "proxy_holdings", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "FTSE100",
        "index_name": "FTSE 100",
        "index_family": "FTSE Russell",
        "index_category": "core_geo",
        "region": "Europe",
        "country_code": "GB",
        "currency": "GBP",
        "is_core": True,
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "^FTSE", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": False},
            {"provider": "yfinance", "provider_symbol": "^FTSE", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": False},
            {"provider": "etf_proxy", "provider_symbol": "ISF.L", "symbol_purpose": "proxy_holdings", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "NIKKEI225",
        "index_name": "Nikkei 225",
        "index_family": "Nikkei",
        "index_category": "core_geo",
        "region": "Asia Pacific",
        "country_code": "JP",
        "currency": "JPY",
        "is_core": True,
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "^N225", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": False},
            {"provider": "yfinance", "provider_symbol": "^N225", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": False},
            {"provider": "etf_proxy", "provider_symbol": "EWJ", "symbol_purpose": "proxy_holdings", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "DEV_INTL",
        "index_name": "Developed International Equity",
        "index_family": "MSCI/FTSE",
        "index_category": "core_geo",
        "region": "Developed ex-North America",
        "country_code": None,
        "currency": "USD",
        "is_core": True,
        "symbols": [
            {"provider": "etf_proxy", "provider_symbol": "IEFA", "symbol_purpose": "proxy_price", "is_primary": True, "is_proxy": True},
            {"provider": "etf_proxy", "provider_symbol": "IEFA", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
        ],
    },
    {
        "index_id": "EM",
        "index_name": "Emerging Markets Equity",
        "index_family": "MSCI/FTSE",
        "index_category": "core_geo",
        "region": "Emerging Markets",
        "country_code": None,
        "currency": "USD",
        "is_core": True,
        "symbols": [
            {"provider": "etf_proxy", "provider_symbol": "VWO", "symbol_purpose": "proxy_price", "is_primary": True, "is_proxy": True},
            {"provider": "etf_proxy", "provider_symbol": "VWO", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
        ],
    },
    {
        "index_id": "FRONTIER",
        "index_name": "Frontier Markets Equity",
        "index_family": "MSCI",
        "index_category": "core_geo",
        "region": "Frontier Markets",
        "country_code": None,
        "currency": "USD",
        "is_core": True,
        "symbols": [
            {"provider": "etf_proxy", "provider_symbol": "FM", "symbol_purpose": "proxy_price", "is_primary": True, "is_proxy": True},
            {"provider": "etf_proxy", "provider_symbol": "FM", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
        ],
    },
]
