"""
Non-core benchmark universe.

These rows extend the benchmark index domain beyond core geographic indices.

Important:
- These are benchmark/proxy rows, not user-owned tradable assets.
- Sector benchmarks use liquid sector ETF proxies.
- Industry/theme benchmarks use liquid ETF proxies.
- All proxy rows must keep is_proxy=True.
"""

SECTOR_INDICES = [
    {
        "index_id": "SEC_COMM",
        "index_name": "Communication Services Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US communication services sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLC", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLC", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLC", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLC", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "SEC_CONS_DISC",
        "index_name": "Consumer Discretionary Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US consumer discretionary sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLY", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLY", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLY", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLY", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "SEC_CONS_STAP",
        "index_name": "Consumer Staples Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US consumer staples sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLP", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLP", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLP", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLP", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "SEC_ENERGY",
        "index_name": "Energy Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US energy sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLE", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLE", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLE", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLE", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "SEC_FINANCIALS",
        "index_name": "Financials Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US financials sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLF", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLF", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLF", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLF", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "SEC_HEALTHCARE",
        "index_name": "Health Care Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US health care sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLV", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLV", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLV", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLV", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "SEC_INDUSTRIALS",
        "index_name": "Industrials Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US industrials sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLI", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLI", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLI", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLI", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "SEC_TECH",
        "index_name": "Information Technology Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US information technology sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLK", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLK", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLK", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLK", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "SEC_MATERIALS",
        "index_name": "Materials Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US materials sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLB", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLB", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLB", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLB", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "SEC_REAL_ESTATE",
        "index_name": "Real Estate Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US real estate sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLRE", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLRE", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLRE", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLRE", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "SEC_UTILITIES",
        "index_name": "Utilities Sector",
        "index_family": "Select Sector SPDR",
        "index_category": "sector",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for US utilities sector benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XLU", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XLU", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLU", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XLU", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
]


INDUSTRY_AND_THEME_INDICES = [
    {
        "index_id": "IND_SEMICONDUCTORS",
        "index_name": "Semiconductors Industry",
        "index_family": "iShares",
        "index_category": "industry",
        "region": "Global",
        "country_code": None,
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for semiconductor industry benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "SOXX", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "SOXX", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "SOXX", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "SOXX", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "SMH", "symbol_purpose": "price_daily", "is_primary": False, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "SMH", "symbol_purpose": "price_intraday", "is_primary": False, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "SMH", "symbol_purpose": "proxy_holdings", "is_primary": False, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "SMH", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "IND_SOFTWARE",
        "index_name": "Software Industry",
        "index_family": "iShares",
        "index_category": "industry",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for software industry benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "IGV", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "IGV", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "IGV", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "IGV", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "THEME_CLOUD",
        "index_name": "Cloud Computing Theme",
        "index_family": "Global X",
        "index_category": "theme",
        "region": "Global",
        "country_code": None,
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for cloud computing benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "CLOU", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "CLOU", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "CLOU", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "CLOU", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "THEME_CYBERSECURITY",
        "index_name": "Cybersecurity Theme",
        "index_family": "First Trust",
        "index_category": "theme",
        "region": "Global",
        "country_code": None,
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for cybersecurity benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "CIBR", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "CIBR", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "CIBR", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "CIBR", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "THEME_AI",
        "index_name": "Artificial Intelligence Theme",
        "index_family": "Global X",
        "index_category": "theme",
        "region": "Global",
        "country_code": None,
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for artificial intelligence benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "AIQ", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "AIQ", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "AIQ", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "AIQ", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "THEME_ROBOTICS",
        "index_name": "Robotics and Automation Theme",
        "index_family": "Global X",
        "index_category": "theme",
        "region": "Global",
        "country_code": None,
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for robotics and automation benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "BOTZ", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "BOTZ", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "BOTZ", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "BOTZ", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "THEME_SOLAR",
        "index_name": "Solar Energy Theme",
        "index_family": "Invesco",
        "index_category": "theme",
        "region": "Global",
        "country_code": None,
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for solar energy benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "TAN", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "TAN", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "TAN", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "TAN", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "THEME_URANIUM_NUCLEAR",
        "index_name": "Uranium and Nuclear Energy Theme",
        "index_family": "Global X",
        "index_category": "theme",
        "region": "Global",
        "country_code": None,
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for uranium and nuclear energy benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "URA", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "URA", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "URA", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "URA", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "IND_BIOTECH",
        "index_name": "Biotechnology Industry",
        "index_family": "SPDR",
        "index_category": "industry",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for biotechnology industry benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "XBI", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "XBI", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XBI", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "XBI", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "IND_MEDICAL_DEVICES",
        "index_name": "Medical Devices Industry",
        "index_family": "iShares",
        "index_category": "industry",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for medical devices industry benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "IHI", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "IHI", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "IHI", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "IHI", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "IND_AEROSPACE_DEFENSE",
        "index_name": "Aerospace and Defense Industry",
        "index_family": "iShares",
        "index_category": "industry",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for aerospace and defense industry benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "ITA", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "ITA", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "ITA", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "ITA", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "THEME_INFRASTRUCTURE",
        "index_name": "Infrastructure Theme",
        "index_family": "Global X",
        "index_category": "theme",
        "region": "United States",
        "country_code": "US",
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for infrastructure benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "PAVE", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "PAVE", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "PAVE", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "PAVE", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "THEME_FINTECH",
        "index_name": "Fintech Theme",
        "index_family": "Global X",
        "index_category": "theme",
        "region": "Global",
        "country_code": None,
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for fintech and digital payments benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "FINX", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "FINX", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "FINX", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "FINX", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "THEME_CLEAN_ENERGY",
        "index_name": "Clean Energy Theme",
        "index_family": "iShares",
        "index_category": "theme",
        "region": "Global",
        "country_code": None,
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for clean energy benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "ICLN", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "ICLN", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "ICLN", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "ICLN", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
    {
        "index_id": "THEME_BATTERY_TECH",
        "index_name": "Battery Technology and Lithium Theme",
        "index_family": "Global X",
        "index_category": "theme",
        "region": "Global",
        "country_code": None,
        "currency": "USD",
        "is_core": False,
        "notes": "ETF proxy for battery technology and lithium benchmark.",
        "symbols": [
            {"provider": "yfinance", "provider_symbol": "LIT", "symbol_purpose": "price_daily", "is_primary": True, "is_proxy": True},
            {"provider": "yfinance", "provider_symbol": "LIT", "symbol_purpose": "price_intraday", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "LIT", "symbol_purpose": "proxy_holdings", "is_primary": True, "is_proxy": True},
            {"provider": "fmp", "provider_symbol": "LIT", "symbol_purpose": "proxy_price", "is_primary": False, "is_proxy": True},
        ],
    },
]


NON_CORE_BENCHMARK_INDICES = SECTOR_INDICES + INDUSTRY_AND_THEME_INDICES
